[project]
name = "myfundfinder"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.3.3",
    "pytz>=2025.2",
    "requests>=2.32.5",
]
