name: Daily Job

on:
  schedule:
    - cron:  '0 9 * * *'
  workflow_dispatch:


jobs:
  build:
    name: build page
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write     
      id-token: write   
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' 
        cache: 'pip'
        
    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Run Main
      run: python3 daily.py
      working-directory: .
      env:
        LIXINGER_TOKEN: ${{ secrets.LIXINGER_TOKEN }}

    - name: Deploy to Cloudflare Pages
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        command: pages deploy --project-name=fund-finder ./output
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'output/'
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4